#!/bin/bash
version=`python3 -c "import electrumfairchains; print(electrumfairchains.version.ELECTRUMFAIRCHAINS_VERSION)"`
sig=`./run_efc -w $SIGNING_WALLET signmessage $SIGNING_ADDRESS $version`
echo "{ \"version\":\"$version\", \"signatures\":{ \"$SIGNING_ADDRESS\":\"$sig\"}}"
